//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahjongDll {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MahjongDll.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The family can&apos;t be dragon or wind in this context..
        /// </summary>
        internal static string InvalidTileFamilyError {
            get {
                return ResourceManager.GetString("InvalidTileFamilyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The tile number is invalid..
        /// </summary>
        internal static string InvalidTileNumberError {
            get {
                return ResourceManager.GetString("InvalidTileNumberError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The tiles count is invalid (must be 2, 3 or 4)..
        /// </summary>
        internal static string InvalidTilesCountError {
            get {
                return ResourceManager.GetString("InvalidTilesCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The tiles count is invalid (must be 14)..
        /// </summary>
        internal static string InvalidTilesCountInHandError {
            get {
                return ResourceManager.GetString("InvalidTilesCountInHandError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The tiles must be from the same family type..
        /// </summary>
        internal static string InvalidTilesFamilyError {
            get {
                return ResourceManager.GetString("InvalidTilesFamilyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The tiles must be a sequence or adjacent numbers if not a pon, pair or kan..
        /// </summary>
        internal static string InvalidTilesSequenceError {
            get {
                return ResourceManager.GetString("InvalidTilesSequenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The tiles must be the same for a count of 2 or 4..
        /// </summary>
        internal static string InvalidTwoOrFourTilesSetError {
            get {
                return ResourceManager.GetString("InvalidTwoOrFourTilesSetError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The list of yakus doesn&quot;t comply properties of the hand..
        /// </summary>
        internal static string InvalidYakuRulesError {
            get {
                return ResourceManager.GetString("InvalidYakuRulesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The list of yakus should contains at least one element..
        /// </summary>
        internal static string InvalidYakusListError {
            get {
                return ResourceManager.GetString("InvalidYakusListError", resourceCulture);
            }
        }
    }
}
