//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MahjongDll {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Rules : global::System.Configuration.ApplicationSettingsBase {
        
        private static Rules defaultInstance = ((Rules)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Rules())));
        
        public static Rules Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RenhouFansCount {
            get {
                return ((int)(this["RenhouFansCount"]));
            }
            set {
                this["RenhouFansCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AllowMultipleYakumans {
            get {
                return ((bool)(this["AllowMultipleYakumans"]));
            }
            set {
                this["AllowMultipleYakumans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Akadora {
            get {
                return ((bool)(this["Akadora"]));
            }
            set {
                this["Akadora"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NagashiMangan {
            get {
                return ((bool)(this["NagashiMangan"]));
            }
            set {
                this["NagashiMangan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool OpenTanyao {
            get {
                return ((bool)(this["OpenTanyao"]));
            }
            set {
                this["OpenTanyao"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Round430Mangan {
            get {
                return ((bool)(this["Round430Mangan"]));
            }
            set {
                this["Round430Mangan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool KazoeYakuman {
            get {
                return ((bool)(this["KazoeYakuman"]));
            }
            set {
                this["KazoeYakuman"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DaisharinYakuman {
            get {
                return ((bool)(this["DaisharinYakuman"]));
            }
            set {
                this["DaisharinYakuman"] = value;
            }
        }
    }
}
